backend:
  name: github
  repo: tapsellorg/TapsellDocument
media_folder: 'src/jekyll/images'
public_folder: '/images'
collections:
  - name: 'data'
    label: 'Data'
    delete: false
    files:
      - label: 'Sidebar'
        delete: false
        name: 'sidebar'
        file: 'src/jekyll/_data/sidebar.yml'
        extension: yml
        fields:
          - label: English
            name: en
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Children
                name: children
                widget: list
                allow_add: true
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Children
                    name: children
                    widget: list
                    allow_add: true
                    fields:
                      - label: Name
                        name: name
                        widget: string
          - label: Persian
            name: fa
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Children
                name: children
                widget: list
                allow_add: true
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Children
                    name: children
                    widget: list
                    allow_add: true
                    fields:
                      - label: Name
                        name: name
                        widget: string
  - name: faq
    label: FAQ
    delete: true
    create: true
    folder: src/jekyll/docs/faq
    identifier_field: permalink
    summary: '{{fields.title}} •• {{fields.lang}} •• {{fields.permalink}}'
    slug: '{{fields.permalink}}-{{fields.lang}}'
    preview_path: '/faq/{{fields.permalink}}'
    editor:
      preview: false
    fields:
      - name: layout
        label: Layout
        widget: hidden
        requied: true
        default: classic-docs
      - name: title
        label: Title
        widget: string
        requied: true
      - name: toc
        label: Table of Contents
        widget: hidden
        default: true
        requied: true
      - name: permalink
        label: Permalink
        widget: string
        requied: true
        hint: 'Url of the page. Ex. /sdk/android/'
        pattern: ['^\/([a-z0-9\-]*[a-z0-9]+\/)*([a-z0-9\-]*[a-z0-9]+)\/$', 'Must start and end with "/". Ex. /sdk/android/']
      - name: lang
        label: Language
        widget: select
        options: ['fa', 'en']
        requied: true
        default: fa
      - name: body
        label: Body
        widget: markdown
        requied: true
  # - name: sdk
  #   label: SDK Docs
  #   delete: true
  #   create: true
  #   folder: src/jekyll/docs/sdk
  #   identifier_field: permalink
  #   summary: '{{fields.title}} •• {{fields.lang}} •• {{fields.permalink}}'
  #   # slug: '{{fields.permalink}}-{{fields.lang}}'
  #   path: '{{fields.platform}}/{{fields.permalink}}-{{fields.lang}}'
  #   preview_path: '/sdk/{{fields.permalink}}'
  #   editor:
  #     preview: false
  #   fields:
  #     - name: layout
  #       label: Layout
  #       widget: hidden
  #       requied: true
  #       default: classic-docs
  #     - name: platform
  #       label: Platform
  #       widget: select
  #       requied: true
  #       options: ['android', 'flutter', 'ios', 'pwa', 'react-native', 'unity']
  #       default: classic-docs
  #     - name: title
  #       label: Title
  #       widget: string
  #       requied: true
  #     - name: toc
  #       label: Table of Contents
  #       widget: boolean
  #       default: true
  #       requied: true
  #     - name: permalink
  #       label: Permalink
  #       widget: string
  #       requied: true
  #       hint: 'Url of the page. Ex. /sdk/android/'
  #       pattern: ['^\/([a-z0-9\-]*[a-z0-9]+\/)*([a-z0-9\-]*[a-z0-9]+)\/$', 'Must start and end with "/". Ex. /sdk/android/']
  #     - name: lang
  #       label: Language
  #       widget: select
  #       options: ['fa', 'en']
  #       requied: true
  #       default: fa
  #     - name: body
  #       label: Body
  #       widget: markdown
  #       requied: true
